# Database connection details, should you want to have a database connection.
# KEEP THIS COMMENTED OUT IN THIS DEFAULT CONFIG OTHERWISE BAD THINGS!
# Do NOT change the ==: value.
database:
  ==: vg.civcraft.mc.civmodcore.dao.ManagedDatasource
  plugin: CivModCore
  user: 'mc_namelayer'
  password: 'minecraft'
  host: localhost
  port: 3306
  database: namelayer
  poolsize: 5
  connection_timeout: 10000
  idle_timeout: 600000
  max_lifetime: 7200000
