name: ${project.artifactId}
version: ${project.version}
main: vg.civcraft.mc.civmodcore.CivModCorePlugin
authors: [valadian, rourke750, ProgrammerDan, Maxopoly, DeadBeef, Protonull, Okx, mindless728, Tealnerd]
website: ${project.url}
api-version: 1.16
commands:
  config: {}
  configsetany:
    permission: cmc.configany
    description: 'Lets you set any config setting for any player'
    usage: '/configany <player|uuid> <settingId> <value>'
  configgetany:
    permission: cmc.configany
    description: 'Lets you get any config setting for any player'
    usage: '/configany <player|uuid> <settingId>'
permissions:
  cmc.config.save:
    default: op
  cmc.configany:
    default: op
  cmc.debug:
    default: op
